services:
  kali:
    image: ${H3RETIK_KALI_IMAGE:-h3retik/kali:v0.0.4}
    build:
      context: .
      dockerfile: Dockerfile.kali
    container_name: ${H3RETIK_KALI_CONTAINER:-h3retik-kali}
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    command: ["/bin/bash", "-lc", "sleep infinity"]
    networks:
      - h3retik-lab
    volumes:
      - ./telemetry:/telemetry
      - ./artifacts:/artifacts

networks:
  h3retik-lab:
    name: h3retik-lab
