services:
  kali:
    image: ${H3RETIK_KALI_IMAGE:-h3retik/kali:v0.0.3}
    build:
      context: .
      dockerfile: Dockerfile.kali
    container_name: ${H3RETIK_KALI_CONTAINER:-jsbb-kali}
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    command: ["/bin/bash", "-lc", "sleep infinity"]
    networks:
      - blackbox-lab
      - juiceshop-blackbox
    volumes:
      - ./telemetry:/telemetry
      - ./artifacts:/artifacts

networks:
  blackbox-lab:
    external: true
    name: blackbox-lab
  juiceshop-blackbox:
    external: true
    name: juiceshop-blackbox
